name: backend-ci
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          cd backend
          python -m pip install -r requirements.txt
      - name: Smoke import
        run: |
          cd backend
          python - <<'PY'
          import importlib
          importlib.import_module("dasherprotect.app")
          print("backend import OK")
          PY
